import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — HireSage",
};

export default function TermsOfServicePage() {
  return (
    <main className="container narrowContainer">
      <div className="stack" style={{ gap: "1.5rem" }}>
        <div>
          <h1>Terms of Service</h1>
          <p className="small">Last updated: April 13, 2026</p>
        </div>

        <section className="stack">
          <h2>1. Acceptance of Terms</h2>
          <p>
            By creating an account or using HireSage, you agree to these Terms
            of Service. If you do not agree, do not use the service.
          </p>
        </section>

        <section className="stack">
          <h2>2. Description of Service</h2>
          <p>
            HireSage is an AI-powered job application assistant that helps you
            create tailored cover letters, analyze job descriptions, manage
            experience stories, and generate other application materials. The
            service uses artificial intelligence (via OpenAI) to generate
            content based on information you provide.
          </p>
        </section>

        <section className="stack">
          <h2>3. AI-Generated Content</h2>
          <p>
            Content generated by HireSage is created with AI assistance and
            should be treated as a starting point, not a finished product. You
            are responsible for:
          </p>
          <ul>
            <li>Reviewing all generated content before use</li>
            <li>
              Verifying the accuracy of any claims, metrics, or statements
            </li>
            <li>
              Ensuring generated materials truthfully represent your
              qualifications and experience
            </li>
            <li>
              Any consequences of submitting AI-assisted materials to employers
            </li>
          </ul>
          <p>
            HireSage does not guarantee that generated content is accurate,
            complete, or suitable for any particular application. While we
            include guardrails to prevent fabricated metrics and claims, you bear
            ultimate responsibility for all materials you submit.
          </p>
        </section>

        <section className="stack">
          <h2>4. Your Account</h2>
          <p>
            You are responsible for maintaining the security of your account
            credentials. You must provide accurate information when creating
            your account and keep your contact information current. You may not
            share your account or allow others to access it.
          </p>
        </section>

        <section className="stack">
          <h2>5. Your Content</h2>
          <p>
            You retain ownership of all content you provide to HireSage,
            including your profile information, resume text, experience stories,
            job descriptions, and notes. By using the service, you grant
            HireSage a limited license to process your content solely for the
            purpose of providing the service to you.
          </p>
          <p>
            You retain ownership of AI-generated outputs (cover letters,
            question banks, etc.) created through your use of the service.
          </p>
        </section>

        <section className="stack">
          <h2>6. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul>
            <li>
              Use the service to generate fraudulent, misleading, or deceptive
              application materials
            </li>
            <li>
              Misrepresent AI-generated content as entirely your own work where
              disclosure is required
            </li>
            <li>
              Attempt to access other users&rsquo; accounts or data
            </li>
            <li>Use the service in violation of any applicable law</li>
            <li>
              Use automated tools to scrape or bulk-access the service
            </li>
            <li>
              Reverse-engineer, decompile, or attempt to extract the source code
              of the service
            </li>
          </ul>
        </section>

        <section className="stack">
          <h2>7. Payments and Subscriptions</h2>
          <p>
            HireSage offers optional paid features including donations and
            subscriptions. All payments are processed by Stripe. Subscription
            terms, pricing, and cancellation policies are presented at the time
            of purchase. You may manage your subscription through the Account
            page or Stripe customer portal.
          </p>
          <p>
            Donations are voluntary and non-refundable. Subscription refunds are
            handled on a case-by-case basis.
          </p>
        </section>

        <section className="stack">
          <h2>8. Service Availability</h2>
          <p>
            We strive to keep HireSage available and reliable, but we do not
            guarantee uninterrupted access. The service may be temporarily
            unavailable due to maintenance, updates, or circumstances beyond our
            control. We reserve the right to modify or discontinue the service
            at any time with reasonable notice.
          </p>
        </section>

        <section className="stack">
          <h2>9. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, HireSage and its operators
            shall not be liable for any indirect, incidental, special,
            consequential, or punitive damages, including but not limited to
            loss of employment opportunities, arising from your use of the
            service.
          </p>
          <p>
            The service is provided &ldquo;as is&rdquo; and &ldquo;as
            available&rdquo; without warranties of any kind, either express or
            implied, including but not limited to implied warranties of
            merchantability, fitness for a particular purpose, or
            non-infringement.
          </p>
        </section>

        <section className="stack">
          <h2>10. Termination</h2>
          <p>
            You may delete your account at any time by contacting us. We may
            suspend or terminate your access if you violate these terms. Upon
            termination, your right to use the service ceases and we may delete
            your data after a reasonable retention period.
          </p>
        </section>

        <section className="stack">
          <h2>11. Changes to These Terms</h2>
          <p>
            We may update these terms from time to time. Continued use of the
            service after changes constitutes acceptance of the revised terms. We
            will notify you of material changes by posting the updated terms on
            this page with a revised date.
          </p>
        </section>

        <section className="stack">
          <h2>12. Governing Law</h2>
          <p>
            These terms are governed by the laws of the United States. Any
            disputes will be resolved in accordance with applicable federal and
            state law.
          </p>
        </section>

        <section className="stack">
          <h2>13. Contact</h2>
          <p>
            If you have questions about these terms, please contact us at{" "}
            <a href="mailto:support@hiresage.com">support@hiresage.com</a>.
          </p>
        </section>
      </div>
    </main>
  );
}
